/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Phase 1 design tokens (see src/theme/tokens.ts)
        brand:          '#6F45FF',
        'brand-ink':    '#3B1E9A',
        'brand-tint':   '#F1ECFF',
        'brand-tint-2': '#E5DBFF',
        live:           '#00D27A',
        'live-tint':    '#DCFBEC',
        'live-ink':     '#003D23',
        warm:           '#FF8A3D',
        'warm-tint':    '#FFF4E4',
        'warm-ink':     '#B54300',
        danger:         '#F43F5E',
        'danger-tint':  '#FFE4E8',
        'danger-ink':   '#A80025',
        ink:            '#0B0B10',
        'ink-2':        '#1C1C22',
        muted:          '#6E6E78',
        'muted-2':      '#A3A3AD',
        line:           '#E7E7EC',
        'line-2':       '#F1F1F4',
        canvas:         '#F5F5F7',
        surface:        '#FFFFFF',

        // Legacy palettes (kept so existing className usages don't break during migration)
        primary: {
          DEFAULT: '#6f45ff',
          50:  '#f3efff',
          100: '#e6dcff',
          200: '#ccb9ff',
          300: '#b396ff',
          400: '#9973ff',
          500: '#6f45ff',
          600: '#5c35e0',
          700: '#4a28c0',
          800: '#381da0',
          900: '#261480',
        },
        neutral: {
          0:    '#ffffff',
          50:   '#f9f9f9',
          100:  '#f5f5f7',
          200:  '#e5e5e5',
          300:  '#d4d4d4',
          400:  '#a3a3a3',
          500:  '#737373',
          600:  '#525252',
          700:  '#404040',
          800:  '#262626',
          900:  '#171717',
          1000: '#000000',
        },
        positive: {
          DEFAULT: '#10b981',
          light: '#d1fae5',
        },
        negative: {
          DEFAULT: '#f43f5e',
          light: '#ffe4e6',
        },
        warning: {
          DEFAULT: '#f97316',
          light: '#ffedd5',
        },
        bg: {
          main: '#F5F5F7',
          surface: '#ffffff',
        },
      },
      fontFamily: {
        sans: ['Inter_400Regular', 'sans-serif'],
        'sans-medium': ['Inter_500Medium', 'sans-serif'],
        'sans-semibold': ['Inter_600SemiBold', 'sans-serif'],
        'sans-bold': ['Inter_700Bold', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '14px',
        xs: '6px',
        sm: '10px',
        md: '14px',
        lg: '18px',
        xl: '24px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
